export const SEARCHED_USERS = 'SEARCHED_USERS';

export const REQUESTED_TOKEN              = 'REQUESTED_TOKEN';
export const RECEIVED_TOKEN               = 'RECEIVED_TOKEN';
export const REVOKE_TOKEN                 = 'REVOKE_TOKEN';
export const RECEIVED_TOKEN_ERROR         = 'RECEIVED_TOKEN_ERROR';

export const REQUESTED_CUSTOMER_DATA      = 'REQUESTED_CUSTOMER_DATA';
export const RECEIVED_CUSTOMER_DATA       = 'RECEIVED_CUSTOMER_DATA';
export const RECEIVED_CUSTOMER_DATA_ERROR = 'RECEIVED_CUSTOMER_DATA_ERROR';

export const RECEIVED_USERS               = 'RECEIVED_USERS';
export const CLEARED_SEARCH_RESULTS       = 'CLEARED_SEARCH_RESULTS';

export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';

export const CHECKED_ADMIN_ACCESS = 'CHECKED_ADMIN_ACCESS';
export const ACCESS_DENIED = 'ACCESS_DENIED';
