export const TOKEN_FETCH               = 'TOKEN_FETCH';
export const TOKEN_FULFILLED           = 'TOKEN_FULFILLED';
export const TOKEN_REVOKE              = 'TOKEN_REVOKE';
export const TOKEN_FETCH_REJECTED      = 'TOKEN_FETCH_REJECTED';

export const CUSTOMER_DATA_FETCH       = 'CUSTOMER_DATA_FETCH';
export const CUSTOMER_DATA_FULFILLED   = 'CUSTOMER_DATA_FULFILLED';
export const CUSTOMER_DATA_FETCH_ERROR = 'CUSTOMER_DATA_FETCH_ERROR';
